ALTER TABLE client
	ALTER COLUMN client_login SET NOT NULL,
	ALTER COLUMN client_password SET NOT NULL,
	ALTER COLUMN mail SET NOT NULL,
	ALTER COLUMN privilege SET NOT NULL;


ALTER TABLE chart
	ALTER COLUMN city SET NOT NULL,
	ALTER COLUMN title SET NOT NULL,
	ALTER COLUMN svg_content SET NOT NULL;


ALTER TABLE branch
	ALTER COLUMN title SET NOT NULL,
	ALTER COLUMN color SET NOT NULL,
	ALTER COLUMN access SET NOT NULL;


ALTER TABLE station
	ALTER COLUMN title SET NOT NULL,
	ALTER COLUMN occupancy SET NOT NULL,
	ALTER COLUMN access SET NOT NULL,
	ALTER COLUMN open_time SET NOT NULL,
	ALTER COLUMN close_time SET NOT NULL;


ALTER TABLE transition
	ALTER COLUMN occupancy SET NOT NULL,
	ALTER COLUMN access SET NOT NULL,
	ALTER COLUMN duration SET NOT NULL,
	ALTER COLUMN open_time SET NOT NULL,
	ALTER COLUMN close_time SET NOT NULL;


ALTER TABLE way
	ALTER COLUMN title SET NOT NULL,
	ALTER COLUMN init_date SET NOT NULL;


ALTER TABLE way_item
	ALTER COLUMN nexus SET NOT NULL,
	ALTER COLUMN step_nomer SET NOT NULL;