CREATE TYPE role_type AS ENUM ('UNSIGNED', 'SIGNED', 'DUTY');
CREATE TYPE access_type AS ENUM ('ACCESSIBLE', 'INACCESSIBLE');
CREATE TYPE nexus_type AS ENUM ('STATION', 'TRANSITION', 'RAILWAY');

CREATE DOMAIN occupancy_level AS SMALLINT CHECK(VALUE BETWEEN 0 AND 10);
CREATE DOMAIN decimal_hexcolor AS INT CHECK(VALUE BETWEEN 0 AND 16777215);