CREATE ROLE IF NOT EXISTS WITH LOGIN PASSWORD 'unsigned_user';
CREATE ROLE IF NOT EXISTS WITH LOGIN PASSWORD 'signed_user';
CREATE ROLE IF NOT EXISTS WITH LOGIN PASSWORD 'duty_user';
CREATE ROLE IF NOT EXISTS WITH LOGIN PASSWORD 'admin_user';
CREATE ROLE IF NOT EXISTS WITH LOGIN PASSWORD 'dev_user';