CREATE TABLE IF NOT EXISTS User (
	ID SERIAL PRIMARY KEY,
	mail VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Duty (
	ID SERIAL PRIMARY KEY,
	mail VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Trajectory (
	ID SERIAL PRIMARY KEY,
	city VARCHAR(255),
	title VARCHAR(255)
	svd_content TEXT
);

CREATE TABLE IF NOT EXISTS Chart (
	ID SERIAL PRIMARY KEY,
	city VARCHAR(255),
	title VARCHAR(255)
	svd_content TEXT
);